### ISSUE TITLE
will the dialogue model checkpoints be released?

### ISSUE THREAD

**Issue by lianyixin** [jokieleung/Maria#1]
hi, it seems dialogue model checkpoints trained on the reddit and oi dataset are not released. will it be released soon? thanks

**Comment by jokieleung** [comment]
Hi Yixin, Sorry for missing your issue and replying so late. Due to the policy of the company, we have no plan to release the ckpt recently, I am sorry for that. If you encounter any issue during re-implementation, plz feel free to contact me.
